// This file is autogenerated. Changes will be overwritten.
#include "TXKPOHTVN7/moc_AuthorizationWidget.cpp"
#include "TXKPOHTVN7/moc_MainWindow.cpp"
#include "TXKPOHTVN7/moc_RegistrationWidget.cpp"
#include "5OXUWOYTCX/moc_ChatWidget.cpp"
#include "5OXUWOYTCX/moc_MessengerWidget.cpp"
#include "5OXUWOYTCX/moc_StackedChatWidget.cpp"
