// This file is autogenerated. Changes will be overwritten.
#include "7EM65HM6UG/moc_Client.cpp"
#include "7EM65HM6UG/moc_ClientThread.cpp"
#include "TXKPOHTVN7/moc_AuthorizationWidget.cpp"
#include "TXKPOHTVN7/moc_ChatWidget.cpp"
#include "TXKPOHTVN7/moc_MainWindow.cpp"
#include "TXKPOHTVN7/moc_RegistrationWidget.cpp"
#include "LOICISCJLG/moc_IMsgProcessor.cpp"
